### ISSUE TITLE
question on adaptability of IS-MBPG

### ISSUE THREAD

**Issue by turmeric-blend** [gaosh/MBPG#1]
hi, im interested in adapting this code for some experimentation. I have a question, is the techniques used for the IS-MBPG variant applicable to Direct Policy Gradient methods - so PG methods without State Value/State-Action Value (Q)/Advantage Value.

**Comment by gaosh** [comment]
Yes, the IS-MBPG itself is a direct policy gradient method and we did not use state values, only linear baselines are used.

**Comment by turmeric-blend** [comment]
hi @gaosh I've notice in your code you have [computed the advantage](https://github.com/gaosh/MBPG/blob/550631a776220d5904ac0f0940f904381fc7943b/Algorithms/MBPG.py#L278) which involves baseline (which is a form of value function). 

I just want to confirm that your method can work for policy methods without advantage computation?

**Comment by gaosh** [comment]
Yes, our algorithm should still work. However, the variance might be larger, and you may need to adjust hyperparameters.
