### ISSUE TITLE
No module named 'garage.tf.envs'

### ISSUE THREAD

**Issue by turmeric-blend** [gaosh/MBPG#2]
Hi,

I tried to run `python MBPG_test.py --env CartPole`
and ran into this error:
```
Traceback (most recent call last):
  File "MBPG_test.py", line 6, in <module>
    from garage.tf.envs import TfEnv
ModuleNotFoundError: No module named 'garage.tf.envs'
```
I have tensorflow 2.0.0 in my environment

**Comment by gaosh** [comment]
Our implementation is based on garage with PyTorch.  Currently, we do not have plans to add support for TensorFlow.

**Comment by turmeric-blend** [comment]
hi @gaosh actually I have both tensorflow 2.0 and pytorch 1.3 in my environment. 

im not sure if this calls tensorflow but your source code still imports `garage.tf` from [here](https://github.com/gaosh/MBPG/blob/550631a776220d5904ac0f0940f904381fc7943b/MBPG_test.py#L6), which is where the issue is occuring

if you are not using tensorflow, then this code from MBPG_test.py importing `from garage.tf.envs import TfEnv` might require tensorflow?

It could also be due to the different versions of garage. which version are you using? I'm using the latest.

**Comment by gaosh** [comment]
`from garage.tf.envs import TfEnv` probably do not require a tf installation. I think the problem comes from the different version of garage. The garage version is `2019.10.1` in my environment.
